#!/bin/bash

function a {

echo  "The most requestable IP"

grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" example_log.log   | sort | uniq -c | sort -gr | head -1

}

function b {
echo "The most requestable page"    
awk '{print $7}' example_log.log |sort | uniq -c | sort -gr | head -1

}

function c {
echo "Count of requests of each IP"
grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"  example_log.log  | sort | uniq -c | sort -gr 
}

function d {
echo "Not found pages"

grep "404" example_log.log  | awk '{print $7}' | sort | uniq -c
}

function e { 
echo "The nost requestable time"    
grep -Eo 25/Apr/2017:[0-9]{2}:[0-9]{2} example_log.log |sort |uniq -c | sort -gr | head -1
}

function f {
echo "Bots"
awk '{print $1,$15,$16}' example_log.log |grep -i bot |sort -gr | uniq
}

case "$1" in  
-a) a ;;
-b) b ;;
-c) c ;;
-d) d ;;
-e) e ;;
-f) f ;;
*) echo "command not found" ;;
esac
